<?php
namespace App\Services;

/**
 * Asset Manager Service
 * Centralized management of CDN URLs, placeholder images, and asset versioning
 */
class AssetManager {
    private static $instance = null;
    private $config;
    
    private function __construct() {
        $configPath = __DIR__ . '/../config/app_config.php';
        if (file_exists($configPath)) {
            $this->config = require $configPath;
        } else {
            // Fallback defaults
            $this->config = [
                'cdn' => [
                    'tailwindcss' => 'https://cdn.tailwindcss.com',
                    'google_fonts' => 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=Space+Mono:wght@400;700&display=swap',
                ],
                'placeholders' => [
                    'menu_item' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
                    'default' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
                ],
                'assets' => [
                    'version' => '1.0.0',
                    'enable_versioning' => false,
                ],
            ];
        }
    }
    
    public static function getInstance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }
    
    /**
     * Get CDN URL by name
     * @param string $name CDN name (e.g., 'tailwindcss', 'google_fonts')
     * @return string CDN URL
     */
    public function getCdnUrl($name) {
        return $this->config['cdn'][$name] ?? '';
    }
    
    /**
     * Get Tailwind CSS CDN URL
     * @return string
     */
    public function getTailwindCssUrl() {
        return $this->getCdnUrl('tailwindcss');
    }
    
    /**
     * Get Google Fonts CDN URL
     * @return string
     */
    public function getGoogleFontsUrl() {
        return $this->getCdnUrl('google_fonts');
    }
    
    /**
     * Get placeholder image URL
     * @param string $type Placeholder type (e.g., 'menu_item', 'default')
     * @return string Placeholder image URL
     */
    public function getPlaceholderImage($type = 'default') {
        return $this->config['placeholders'][$type] ?? $this->config['placeholders']['default'] ?? '';
    }
    
    /**
     * Get asset URL with optional versioning
     * @param string $path Asset path relative to public directory
     * @return string Full asset URL
     */
    public function getAssetUrl($path) {
        $baseUrl = defined('BASE_URL') ? BASE_URL : '';
        $version = '';
        
        if ($this->config['assets']['enable_versioning'] ?? false) {
            $version = '?v=' . ($this->config['assets']['version'] ?? '1.0.0');
        }
        
        // Remove leading slash if present
        $path = ltrim($path, '/');
        
        return $baseUrl . '/' . $path . $version;
    }
    
    /**
     * Generate the Tailwind CSS markup.
     *
     * Performance-first:
     *   - Prefer the locally precompiled static file at
     *     public/assets/css/tailwind.min.css (generated by
     *     build/tailwind/build.sh, ~25 KB gzipped, cacheable forever).
     *   - Fall back to the runtime CDN ONLY if the compiled file is
     *     missing (new environment or first-time install) so pages
     *     never render unstyled.
     *
     * @return string HTML markup (<link> preferred over <script>).
     */
    public function getTailwindCssScript() {
        $compiled = dirname(__DIR__, 2) . '/public/assets/css/tailwind.min.css';
        if (is_file($compiled)) {
            $baseUrl = defined('BASE_URL') ? BASE_URL : '';
            $v = (int) @filemtime($compiled);
            $href = $baseUrl . '/assets/css/tailwind.min.css?v=' . $v;
            $esc = htmlspecialchars($href, ENT_QUOTES, 'UTF-8');
            // Preload + high-fetchpriority for the LCP-critical stylesheet.
            return '<link rel="preload" as="style" href="' . $esc . '" fetchpriority="high">'
                 . '<link rel="stylesheet" href="' . $esc . '" fetchpriority="high">';
        }
        // Fallback (development only) — the CDN runtime JIT is ~370KB and
        // blocks rendering while it compiles utility classes in the browser.
        $url = $this->getTailwindCssUrl();
        return $url ? '<script src="' . htmlspecialchars($url) . '"></script>' : '';
    }

    /**
     * Generate the Google Fonts markup using the "print → onload" trick:
     *   1. Preconnect so the TLS handshake happens in parallel with HTML
     *      parsing.
     *   2. Request the stylesheet with media="print" so it is NOT render
     *      blocking, then swap it to media="all" once loaded.
     *   3. Provide a <noscript> fallback for JS-disabled clients.
     *
     * The font-display:swap is already baked in via the &display=swap param
     * in app_config.php, so FOUT is handled gracefully by the browser.
     *
     * @return string HTML markup
     */
    public function getGoogleFontsLink() {
        $url = $this->getGoogleFontsUrl();
        if (!$url) { return ''; }
        $esc = htmlspecialchars($url, ENT_QUOTES, 'UTF-8');
        return
            '<link rel="preconnect" href="https://fonts.googleapis.com" crossorigin>'
          . '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
          . '<link rel="preload" as="style" href="' . $esc . '">'
          . '<link rel="stylesheet" href="' . $esc . '" media="print" onload="this.media=\'all\';this.onload=null">'
          . '<noscript><link rel="stylesheet" href="' . $esc . '"></noscript>';
    }
}

