import 'dart:async';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../config/theme.dart';
import '../../auth/cubit/auth_cubit.dart';
import '../../auth/cubit/auth_state.dart';
import '../widgets/otp_code_input.dart';

/// Post-login screen shown when the account has TOTP 2FA enabled. The
/// user enters the current 6-digit code from their authenticator app;
/// on success the AuthCubit exchanges the challenge for a bearer
/// token and we transition to [Authenticated].
///
/// The server-side challenge TTL is surfaced as a live countdown so
/// users understand why they suddenly need to retry if they leave the
/// phone idle on this screen.
class TotpChallengeScreen extends StatefulWidget {
  const TotpChallengeScreen({super.key});

  @override
  State<TotpChallengeScreen> createState() => _TotpChallengeScreenState();
}

class _TotpChallengeScreenState extends State<TotpChallengeScreen> {
  final TextEditingController _codeController = TextEditingController();
  int _secondsLeft = 300;
  Timer? _timer;
  bool _submitting = false;
  bool _sending = false;
  String _method = 'totp';
  bool _codeRequested = false;

  @override
  void initState() {
    super.initState();
    // Rebuild the "Doğrula" button every time digits change so its
    // disabled state tracks the current code length. OtpCodeInput only
    // calls setState on itself; it doesn't notify the parent.
    _codeController.addListener(() {
      if (mounted) setState(() {});
    });
    final state = context.read<AuthCubit>().state;
    if (state is TwoFactorChallengeRequired) {
      _secondsLeft = state.expiresInSeconds;
      _method = state.defaultMethod.isNotEmpty ? state.defaultMethod : 'totp';
      // TOTP codes are generated by the authenticator app, so no server
      // roundtrip is needed. For any other method we auto-trigger the
      // first code delivery so the user doesn't stare at an empty screen.
      if (_method != 'totp') {
        _codeRequested = true;
        WidgetsBinding.instance.addPostFrameCallback((_) => _sendCode(silent: true));
      }
    }
    _timer = Timer.periodic(const Duration(seconds: 1), (_) {
      if (!mounted) return;
      if (_secondsLeft <= 0) {
        _timer?.cancel();
        return;
      }
      setState(() => _secondsLeft--);
    });
  }

  Future<void> _sendCode({bool silent = false}) async {
    if (_sending) return;
    setState(() => _sending = true);
    final res = await context.read<AuthCubit>().send2FACode(_method);
    if (!mounted) return;
    setState(() {
      _sending = false;
      _codeRequested = res['success'] == true || _codeRequested;
    });
    if (!silent) {
      final msg = (res['success'] == true)
          ? '${_methodLabel(_method)} üzerinden kod gönderildi'
          : (res['error']?.toString() ?? 'Kod gönderilemedi');
      ScaffoldMessenger.of(context)
        ..hideCurrentSnackBar()
        ..showSnackBar(SnackBar(
          content: Text(msg),
          backgroundColor:
              res['success'] == true ? AppColors.success : AppColors.error,
          behavior: SnackBarBehavior.floating,
        ));
    }
  }

  String _methodLabel(String m) {
    switch (m) {
      case 'totp':
        return 'Authenticator';
      case 'whatsapp':
        return 'WhatsApp';
      case 'email':
        return 'E-posta';
      case 'sms':
        return 'SMS';
    }
    return m;
  }

  IconData _methodIcon(String m) {
    switch (m) {
      case 'whatsapp':
        return Icons.chat_rounded;
      case 'email':
        return Icons.mark_email_unread_rounded;
      case 'sms':
        return Icons.sms_rounded;
      case 'totp':
      default:
        return Icons.phonelink_lock_rounded;
    }
  }

  String _methodSubtitle(String m) {
    switch (m) {
      case 'whatsapp':
        return 'WhatsApp üzerinden gönderilen 6 haneli kodu girin';
      case 'email':
        return 'E-postanıza gönderilen 6 haneli kodu girin';
      case 'sms':
        return 'Telefonunuza gönderilen 6 haneli kodu girin';
      case 'totp':
      default:
        return 'Authenticator uygulamanızdaki 6 haneli kodu girin';
    }
  }

  @override
  void dispose() {
    _timer?.cancel();
    _codeController.dispose();
    super.dispose();
  }

  Future<void> _submit(String code) async {
    if (_submitting) return;
    setState(() => _submitting = true);
    await context.read<AuthCubit>().verifyTwoFactor(code, method: _method);
    if (!mounted) return;
    // Cubit may have restored the challenge state on failure; clear
    // the digits so the user can retype. If it emitted Authenticated
    // or AuthInitial we've already navigated away by now.
    setState(() => _submitting = false);
    _codeController.clear();
  }

  void _cancel() {
    context.read<AuthCubit>().cancelTwoFactorChallenge();
  }

  String _formatSeconds(int s) {
    final m = (s ~/ 60).toString().padLeft(2, '0');
    final r = (s % 60).toString().padLeft(2, '0');
    return '$m:$r';
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return BlocConsumer<AuthCubit, AuthState>(
      // Re-render on every state change so the error banner flashes
      // through instantly when verifyTwoFactor emits AuthError.
      listenWhen: (prev, curr) => curr is AuthError,
      listener: (ctx, state) {
        if (state is AuthError) {
          HapticFeedback.heavyImpact();
          ScaffoldMessenger.of(ctx)
            ..hideCurrentSnackBar()
            ..showSnackBar(SnackBar(
              content: Text(state.message),
              backgroundColor: AppColors.error,
              behavior: SnackBarBehavior.floating,
            ));
        }
      },
      buildWhen: (prev, curr) =>
          curr is TwoFactorChallengeRequired ||
          curr is Authenticated ||
          curr is AuthInitial,
      builder: (context, state) {
        if (state is! TwoFactorChallengeRequired) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        return Scaffold(
          backgroundColor: Theme.of(context).scaffoldBackgroundColor,
          resizeToAvoidBottomInset: true,
          body: SafeArea(
            child: SingleChildScrollView(
              padding: EdgeInsets.only(
                left: 24,
                right: 24,
                bottom: 16 + MediaQuery.of(context).viewInsets.bottom,
              ),
              child: Column(
                children: [
                  const SizedBox(height: 24),
                  Align(
                    alignment: Alignment.centerLeft,
                    child: IconButton(
                      onPressed: _cancel,
                      icon: Icon(
                        Icons.arrow_back_rounded,
                        color: isDark
                            ? AppColors.darkTextPrimary
                            : AppColors.textPrimary,
                      ),
                    ),
                  ),
                  const SizedBox(height: 4),
                  _Hero(
                    businessLogo: state.businessLogo,
                    secondsLeft: _secondsLeft,
                  ),
                  const SizedBox(height: 20),
                  Text(
                    '2 Adımlı Doğrulama',
                    style: TextStyle(
                      fontSize: 22,
                      fontWeight: FontWeight.w700,
                      color: isDark
                          ? AppColors.darkTextPrimary
                          : AppColors.textPrimary,
                      letterSpacing: -0.3,
                    ),
                  ),
                  const SizedBox(height: 6),
                  Text(
                    _methodSubtitle(_method),
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      fontSize: 13,
                      color: isDark
                          ? AppColors.darkTextSecondary
                          : AppColors.textSecondary,
                      height: 1.4,
                    ),
                  ),
                  if ((state.displayName ?? '').isNotEmpty) ...[
                    const SizedBox(height: 14),
                    _Identity(
                      displayName: state.displayName!,
                      roleLabel: state.roleLabel,
                      businessName: state.businessName,
                    ),
                  ],
                  if (state.methods.length > 1) ...[
                    const SizedBox(height: 14),
                    _MethodPicker(
                      methods: state.methods,
                      current: _method,
                      labelFor: _methodLabel,
                      iconFor: _methodIcon,
                      onPick: _submitting
                          ? null
                          : (m) {
                              if (m == _method) return;
                              setState(() {
                                _method = m;
                                _codeRequested = false;
                              });
                              _codeController.clear();
                              if (m != 'totp') {
                                _sendCode();
                              }
                            },
                    ),
                  ],
                  const SizedBox(height: 20),
                  OtpCodeInput(
                    controller: _codeController,
                    enabled: !_submitting && _secondsLeft > 0,
                    onCompleted: _submit,
                  ),
                  const SizedBox(height: 10),
                  _Timer(secondsLeft: _secondsLeft, format: _formatSeconds),
                  if (_method != 'totp') ...[
                    const SizedBox(height: 8),
                    TextButton.icon(
                      onPressed: (_sending || _secondsLeft <= 0)
                          ? null
                          : () => _sendCode(),
                      icon: Icon(
                        _sending
                            ? Icons.hourglass_top_rounded
                            : Icons.refresh_rounded,
                        size: 16,
                      ),
                      label: Text(
                        _sending
                            ? 'Gönderiliyor…'
                            : (_codeRequested
                                ? 'Kodu tekrar gönder'
                                : 'Kodu ${_methodLabel(_method)} ile gönder'),
                        style: const TextStyle(
                          fontSize: 13,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ],
                  const SizedBox(height: 16),
                  SizedBox(
                    width: double.infinity,
                    height: 52,
                    child: ElevatedButton(
                      onPressed: (_submitting ||
                              _secondsLeft <= 0 ||
                              _codeController.text.length != 6)
                          ? null
                          : () => _submit(_codeController.text),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primary,
                        foregroundColor: Colors.white,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(14),
                        ),
                      ),
                      child: _submitting
                          ? const SizedBox(
                              width: 22,
                              height: 22,
                              child: CircularProgressIndicator(
                                strokeWidth: 2.2,
                                color: Colors.white,
                              ),
                            )
                          : const Text(
                              'Doğrula',
                              style: TextStyle(
                                fontSize: 15,
                                fontWeight: FontWeight.w700,
                              ),
                            ),
                    ),
                  ),
                  const SizedBox(height: 24),
                  TextButton(
                    onPressed: _submitting ? null : _cancel,
                    child: const Text(
                      'Vazgeç ve farklı hesapla giriş yap',
                      style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                        color: AppColors.primary,
                      ),
                    ),
                  ),
                  const SizedBox(height: 8),
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}

class _Hero extends StatelessWidget {
  final String? businessLogo;
  final int secondsLeft;
  const _Hero({required this.secondsLeft, this.businessLogo});

  @override
  Widget build(BuildContext context) {
    final hasLogo = businessLogo != null && businessLogo!.isNotEmpty;
    return SizedBox(
      width: 88,
      height: 88,
      child: Stack(
        clipBehavior: Clip.none,
        children: [
          Container(
            width: 88,
            height: 88,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              gradient: AppColors.brandGradient,
              boxShadow: [
                BoxShadow(
                  color: AppColors.primary.withValues(alpha: 0.25),
                  blurRadius: 22,
                  offset: const Offset(0, 6),
                ),
              ],
            ),
            alignment: Alignment.center,
            child: hasLogo
                ? Padding(
                    padding: const EdgeInsets.all(4),
                    child: ClipOval(
                      child: CachedNetworkImage(
                        imageUrl: businessLogo!,
                        fit: BoxFit.cover,
                        errorWidget: (_, __, ___) => const Icon(
                          Icons.shield_moon_rounded,
                          size: 40,
                          color: Colors.white,
                        ),
                      ),
                    ),
                  )
                : const Icon(
                    Icons.shield_moon_rounded,
                    size: 40,
                    color: Colors.white,
                  ),
          ),
          Positioned(
            right: -2,
            bottom: -2,
            child: Container(
              width: 34,
              height: 34,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: AppColors.success,
                border: Border.all(
                  color: Theme.of(context).scaffoldBackgroundColor,
                  width: 3,
                ),
              ),
              child: const Icon(
                Icons.qr_code_2_rounded,
                color: Colors.white,
                size: 18,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _Identity extends StatelessWidget {
  final String displayName;
  final String? roleLabel;
  final String? businessName;
  const _Identity({
    required this.displayName,
    this.roleLabel,
    this.businessName,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
      decoration: BoxDecoration(
        color: (isDark ? AppColors.darkCard : Colors.white),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: isDark ? AppColors.darkBorder : AppColors.border,
          width: 1,
        ),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            displayName,
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: isDark
                  ? AppColors.darkTextPrimary
                  : AppColors.textPrimary,
            ),
          ),
          if ((businessName ?? '').isNotEmpty || (roleLabel ?? '').isNotEmpty)
            Padding(
              padding: const EdgeInsets.only(top: 2),
              child: Text(
                [
                  if ((roleLabel ?? '').isNotEmpty) roleLabel!,
                  if ((businessName ?? '').isNotEmpty) businessName!,
                ].join(' · '),
                style: TextStyle(
                  fontSize: 12,
                  color: isDark
                      ? AppColors.darkTextSecondary
                      : AppColors.textSecondary,
                ),
              ),
            ),
        ],
      ),
    );
  }
}

class _MethodPicker extends StatelessWidget {
  final List<String> methods;
  final String current;
  final String Function(String) labelFor;
  final IconData Function(String) iconFor;
  final void Function(String)? onPick;

  const _MethodPicker({
    required this.methods,
    required this.current,
    required this.labelFor,
    required this.iconFor,
    required this.onPick,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return SizedBox(
      height: 40,
      child: ListView.separated(
        scrollDirection: Axis.horizontal,
        shrinkWrap: true,
        itemCount: methods.length,
        separatorBuilder: (_, __) => const SizedBox(width: 8),
        itemBuilder: (ctx, i) {
          final m = methods[i];
          final selected = m == current;
          return InkWell(
            onTap: onPick == null ? null : () => onPick!(m),
            borderRadius: BorderRadius.circular(100),
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 160),
              padding:
                  const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
              decoration: BoxDecoration(
                color: selected
                    ? AppColors.primary
                    : (isDark ? AppColors.darkSurface : Colors.white),
                borderRadius: BorderRadius.circular(100),
                border: Border.all(
                  color: selected
                      ? AppColors.primary
                      : (isDark
                          ? AppColors.darkBorder
                          : AppColors.border),
                  width: 1,
                ),
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(
                    iconFor(m),
                    size: 16,
                    color: selected
                        ? Colors.white
                        : (isDark
                            ? AppColors.darkTextPrimary
                            : AppColors.textPrimary),
                  ),
                  const SizedBox(width: 6),
                  Text(
                    labelFor(m),
                    style: TextStyle(
                      fontSize: 12.5,
                      fontWeight: FontWeight.w700,
                      color: selected
                          ? Colors.white
                          : (isDark
                              ? AppColors.darkTextPrimary
                              : AppColors.textPrimary),
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}

class _Timer extends StatelessWidget {
  final int secondsLeft;
  final String Function(int) format;
  const _Timer({required this.secondsLeft, required this.format});

  @override
  Widget build(BuildContext context) {
    final expired = secondsLeft <= 0;
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(
          expired ? Icons.timer_off_rounded : Icons.timer_rounded,
          size: 14,
          color: expired
              ? AppColors.error
              : (isDark
                  ? AppColors.darkTextSecondary
                  : AppColors.textSecondary),
        ),
        const SizedBox(width: 6),
        Text(
          expired
              ? 'Süre doldu, lütfen tekrar giriş yapın'
              : 'Süre: ${format(secondsLeft)}',
          style: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w500,
            color: expired
                ? AppColors.error
                : (isDark
                    ? AppColors.darkTextSecondary
                    : AppColors.textSecondary),
          ),
        ),
      ],
    );
  }
}
